name: Terraform CI

on:
    push:
        branches: [ main ]
    pull_request:
        branches:
            - main

jobs:
    TF_build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Set up Terraform
              uses: hashicorp/setup-terraform@v3

            - name: Terraform fmt -check
              id: tf_fmt
              run: terraform fmt
              continue-on-error: true

            - name: Terraform validate
              id: tf_validate
              run: terraform validate
              continue-on-error: true

            - name: Setup TFLint
              id: tflint_setup
              uses: terraform-linters/setup-tflint@v4
              with:
                tflint_version: v0.50.3
              continue-on-error: true
        
            - name: Init TFLint
              id: tflint_init
              run: tflint --init
              env:
                GITHUB_TOKEN: ${{ github.token }}
              continue-on-error: true
        
            - name: Run TFLint
              id: tflint_run
              run: tflint -f compact
              continue-on-error: true

            - name: Comment on workflow
              run: |
                printf "terraform fmt: ${{toJson(steps.tf_fmt)}}\n
                terraform validate: ${{toJson(steps.tf_validate)}}\n
                terraform lint_setup: ${{toJson(steps.tflint_setup)}}\n
                terraform lint_init: ${{toJson(steps.tflint_init)}}\n
                terraform lint_run: ${{toJson(steps.tflint_run)}}"